### ISSUE TITLE
role "_healthcheck" does not exist

### ISSUE THREAD

**Issue by dan-developer** [pavouk-0/postgres-xl-docker#52]
Using the composer file, I get this error in the output of both cordinators.

```yml
version: "3"
services:
  db_gtm_1:
    environment:
      - PG_HOST=0.0.0.0
      - PG_NODE=gtm_1
      - PG_PORT=6666
    build: .
    command: docker-cmd-gtm
    entrypoint: docker-entrypoint-gtm
    volumes:
      - db_gtm_1:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-gtm"]
  db_coord_1:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=coord_1
      - PG_PORT=5432
    build: .
    command: docker-cmd-coord
    entrypoint: docker-entrypoint-coord
    volumes:
      - db_coord_1:/var/lib/postgresql
    depends_on:
      - db_gtm_1
    networks:
      - db_a
      - db_b
    healthcheck:
      test: ["CMD", "docker-healthcheck-coord"]
  db_coord_2:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=coord_2
      - PG_PORT=5432
    build: .
    command: docker-cmd-coord
    entrypoint: docker-entrypoint-coord
    volumes:
      - db_coord_2:/var/lib/postgresql
    depends_on:
      - db_gtm_1
    networks:
      - db_a
      - db_b
    healthcheck:
      test: ["CMD", "docker-healthcheck-coord"]
  db_data_1:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=data_1
      - PG_PORT=5432
    build: .
    command: docker-cmd-data
    entrypoint: docker-entrypoint-data
    depends_on:
      - db_gtm_1
    volumes:
      - db_data_1:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-data"]
  db_data_2:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=data_2
      - PG_PORT=5432
    build: .
    command: docker-cmd-data
    entrypoint: docker-entrypoint-data
    depends_on:
      - db_gtm_1
    volumes:
      - db_data_2:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-data"]
volumes:
  db_gtm_1: {}
  db_coord_1: {}
  db_coord_2: {}
  db_data_1: {}
  db_data_2: {}
networks:
  db_a:
  db_b:
```

Output:

2020-01-08 17:38:50.664 UTC [47] FATAL:  role "_healthcheck" does not exist
2020-01-08 17:39:23.778 UTC [56] ERROR:  No Datanode defined in cluster
2020-01-08 17:39:23.778 UTC [56] HINT:  You need to define at least 1 Datanode with CREATE NODE.
2020-01-08 17:39:23.778 UTC [56] STATEMENT:  CREATE ROLE _healthcheck NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
2020-01-08 17:39:23.785 UTC [58] ERROR:  role "_healthcheck" does not exist
2020-01-08 17:39:23.785 UTC [58] STATEMENT:  CREATE DATABASE _healthcheck OWNER _healthcheck;
2020-01-08 17:39:23.789 UTC [60] FATAL:  role "_healthcheck" does not exist
2020-01-08 17:39:23.792 UTC [63] FATAL:  role "_healthcheck" does not exist
2020-01-08 17:39:59.939 UTC [72] ERROR:  No Datanode defined in cluster
2020-01-08 17:39:59.939 UTC [72] HINT:  You need to define at least 1 Datanode with CREATE NODE.
2020-01-08 17:39:59.939 UTC [72] STATEMENT:  CREATE ROLE _healthcheck NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
2020-01-08 17:39:59.947 UTC [74] ERROR:  role "_healthcheck" does not exist
2020-01-08 17:39:59.947 UTC [74] STATEMENT:  CREATE DATABASE _healthcheck OWNER _healthcheck;
2020-01-08 17:39:59.951 UTC [76] FATAL:  role "_healthcheck" does not exist
2020-01-08 17:39:59.955 UTC [79] FATAL:  role "_healthcheck" does not exist

**Comment by tiredpixel** [comment]
Sounds like the init process had some issue.
Double-check the networks that were created. What are their subnets?
If you've been trying some stuff on it before, say before initing, then it won't work. In that case, I recommend that you tear it down, delete the ~data~ volumes, prepare your init queries (or use the example file), then spin them up and init it immediately.
Does that help?

**Comment by tiredpixel** [comment]
The first time the cluster is started, some error messages like the above are expected, until it's initted, and until that's been detected and the healthcheck user and db autocreated.
Note also that Postgres-XL has some nasty locking issues with coordinators; I've tried to work around it by adding a random sleep, but it's possible you were unlucky.

**Comment by dan-developer** [comment]
Isn't it starting out of order?

![image](https://user-images.githubusercontent.com/10473169/72003152-884bbe00-3227-11ea-91b9-c66cf6b5f6e4.png)

**Comment by tiredpixel** [comment]
It's fine to start out of order. You can't control that in Swarm, anyway—and even if you could, it wouldn't help for crashes and such.

**Comment by tiredpixel** [comment]
The healthchecks are pretty advanced, and 'deep' healthchecks. Once it's initted successfully, the healthchecks should activate, and thereafter, the cluster will autoheal if there's a networking issue (very common in Docker Swarm, in my experience), or certain types of other Postgres-XL issues (also common, or at least was for me in the past).

**Comment by dan-developer** [comment]
Understand.
But I'm not using docker swarm but docker-compose up -d

**Comment by dan-developer** [comment]
I tried using the docker swarm right now, and was unsuccessful.

**Comment by tiredpixel** [comment]
Unsuccessful in which way? What went wrong? Or what error did you get? Which steps did you follow to init the cluster? What topology does the cluster have? Which version of Postgres-XL are you installing? Which version of Docker and Docker Compose are you using? What does your Compose file look like?

**Comment by dan-developer** [comment]
Docker swarm compose file:

```yml
version: "3.7"

x-custom:
  shared_image: &shared_image
    image: pavouk0/postgres-xl:XL_10_R1_1-313-g31dfe47

services:
  #-----------------------------------------------------------------------------
  db_gtm_1:
    environment:
      - PG_HOST=0.0.0.0
      - PG_NODE=gtm_1
      - PG_PORT=6666
    <<: *shared_image
    command: docker-cmd-gtm
    entrypoint: docker-entrypoint-gtm
    volumes:
      - db_gtm_1:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-gtm"]
#    deploy:
#      placement:
#        constraints:
#          - node.labels.grp == dbxl # assumes shared volume storage, or 1-node
  db_coord_1:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=coord_1
      - PG_PORT=5432
    <<: *shared_image
    command: docker-cmd-coord
    entrypoint: docker-entrypoint-coord
    volumes:
      - db_coord_1:/var/lib/postgresql
    networks:
      - db_a
      - db_b
    healthcheck:
      test: ["CMD", "docker-healthcheck-coord"]
#    deploy:
#      placement:
#        constraints:
#          - node.labels.grp == dbxl # assumes shared volume storage, or 1-node
  db_coord_2:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=coord_2
      - PG_PORT=5432
    <<: *shared_image
    command: docker-cmd-coord
    entrypoint: docker-entrypoint-coord
    volumes:
      - db_coord_2:/var/lib/postgresql
    networks:
      - db_a
      - db_b
    healthcheck:
      test: ["CMD", "docker-healthcheck-coord"]
#    deploy:
#      placement:
#        constraints:
#          - node.labels.grp == dbxl # assumes shared volume storage, or 1-node
  db_data_1:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=data_1
      - PG_PORT=5432
    <<: *shared_image
    command: docker-cmd-data
    entrypoint: docker-entrypoint-data
    volumes:
      - db_data_1:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-data"]
#    deploy:
#      placement:
#        constraints:
#          - node.labels.grp == dbxl # assumes shared volume storage, or 1-node
  db_data_2:
    environment:
      - PG_GTM_HOST=db_gtm_1
      - PG_GTM_PORT=6666
      - PG_HOST=0.0.0.0
      - PG_NODE=data_2
      - PG_PORT=5432
    <<: *shared_image
    command: docker-cmd-data
    entrypoint: docker-entrypoint-data
    volumes:
      - db_data_2:/var/lib/postgresql
    networks:
      - db_a
    healthcheck:
      test: ["CMD", "docker-healthcheck-data"]
#    deploy:
#      placement:
#        constraints:
#          - node.labels.grp == dbxl # assumes shared volume storage, or 1-node
  #-----------------------------------------------------------------------------
volumes:
  db_gtm_1: {}
  db_coord_1: {}
  db_coord_2: {}
  db_data_1: {}
  db_data_2: {}
networks:
  db_a:
    driver: overlay
    internal: true
  db_b:
    driver: overlay
    internal: true
```

Error in coordinator 1 and 2:

2020-01-08 17:38:50.664 UTC [47] FATAL: role "_healthcheck" does not exist
2020-01-08 17:39:23.778 UTC [56] ERROR: No Datanode defined in cluster
2020-01-08 17:39:23.778 UTC [56] HINT: You need to define at least 1 Datanode with CREATE NODE.
2020-01-08 17:39:23.778 UTC [56] STATEMENT: CREATE ROLE _healthcheck NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
2020-01-08 17:39:23.785 UTC [58] ERROR: role "_healthcheck" does not exist
2020-01-08 17:39:23.785 UTC [58] STATEMENT: CREATE DATABASE _healthcheck OWNER _healthcheck;
2020-01-08 17:39:23.789 UTC [60] FATAL: role "_healthcheck" does not exist
2020-01-08 17:39:23.792 UTC [63] FATAL: role "_healthcheck" does not exist
2020-01-08 17:39:59.939 UTC [72] ERROR: No Datanode defined in cluster
2020-01-08 17:39:59.939 UTC [72] HINT: You need to define at least 1 Datanode with CREATE NODE.
2020-01-08 17:39:59.939 UTC [72] STATEMENT: CREATE ROLE _healthcheck NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
2020-01-08 17:39:59.947 UTC [74] ERROR: role "_healthcheck" does not exist
2020-01-08 17:39:59.947 UTC [74] STATEMENT: CREATE DATABASE _healthcheck OWNER _healthcheck;
2020-01-08 17:39:59.951 UTC [76] FATAL: role "_healthcheck" does not exist
2020-01-08 17:39:59.955 UTC [79] FATAL: role "_healthcheck" does not exist

To reproduce:

docker stack deploy -c docker-compose.swarm.yml postgresxl
